version: '3.9'

services:
  postgres:
    ports:
      - "54321:5432"
    image: postgres
    container_name: postgres
    volumes:
      - /home/razind/.pg/pg_data/shcool:/var/lib/postgresql/data
    env_file:
      - .env

  flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask
    volumes:
      - /home/razind/.uploads/images/shcool:/app/app/static/upload
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    expose:
      - 8080

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - flask
    ports:
      - "8080:80"
