"""empty message

Revision ID: 8b19a381065b
Revises: 6e1de6f363c0
Create Date: 2024-06-29 17:26:03.578728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b19a381065b'
down_revision = '6e1de6f363c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=250), nullable=False))
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint(None, ['login'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
