"""empty message

Revision ID: 91110a172a2f
Revises: b1770cd29d7e
Create Date: 2024-06-29 16:51:32.476737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91110a172a2f'
down_revision = 'b1770cd29d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('date_posted')
        batch_op.drop_column('password')
        batch_op.drop_column('login')

    # ### end Alembic commands ###
